### ISSUE TITLE
Google OAuth2 - Update README for Google OAuth2 Simple Example

### ISSUE THREAD

**Issue by jandix** [jandix/sealr#17]
Write a description of the code found in the R file. It should also include some of the information given on the [Google Open ID website](https://developers.google.com/identity/protocols/OpenIDConnect#discovery). 
:warning: The token expires after one hour. The user has to implement a refresh token path!

**Comment by pr130** [comment]
@jandix :  write two - three sentences about OIDC

@friep link google website + steps to the relevant code in the example.
