### ISSUE TITLE
Refactoring: change interface of functions to return TRUE/FALSE

### ISSUE THREAD

**Issue by pr130** [jandix/sealr#18]
we could return TRUE / FALSE instead of forwarding within the function itself. 

This would leave more possibilities to the user. 

e.g. currently it is only possible to preempt one filter which makes more granular authorization (e.g. per endpoint) impossible. If the function only returned TRUE / FALSE the user could also use it inside endpoints (couldn't they?). 
alternatively we could try to cut the functions so that there is always a function that does the check that returns TRUE / FALSE and a corresponding filter function that forwards..

@jandix : what do you think?

**Comment by jandix** [comment]
That might be a possible. However, I would rather prefer to use the functions as a "middleware". However, as you mention, we can define two functions for each filter.

**Comment by pr130** [comment]
I think two functions is a good compromise. 

we should establish a good naming convention for those functions with a prefix / suffix.  Let's talk about that in our next call.

**Comment by pr130** [comment]
```
sealr_authenticate("jwt") {
   is_auth <- switch(strategy) 
     jwt =  jwt_is_authed()
   if (is_auth) forward()
   else :bomb: 
}
```

**Comment by pr130** [comment]
one interface function to avoid code duplication.
