### ISSUE TITLE
JWT - check if token is expired

### ISSUE THREAD

**Issue by pr130** [jandix/sealr#20]
as per #9 , jose decode does not fail automatically if the token is expired.

hence, we should check the exp claim ourselves (if it is there).

Open question: 
what to do with that information? Return 401? 
how can the user know that the token expired? 
can we redirect to a refresh endpoint? :thinking: 
@jandix: your opinion?

**Comment by jandix** [comment]
I would argue that we should test the expiry date similar to the Google OAuth test. We should definitely return a 401. All other functionalities, such as refresh token and user checks, have to be transformed outside the authorization function. However, we should provide design samples in the docs.
