### ISSUE TITLE
JWT - check for vulnerability 

### ISSUE THREAD

**Issue by pr130** [jandix/sealr#22]
ensure that we are safeguarded against this vulnerability: 
https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries//

**Comment by pr130** [comment]
i don't think our `jwt` function is affected by this: 

"I suggest that JWT libraries add an algorithm parameter to their verification function:

verify(string token, string algorithm, string verificationKey)

The server should already know what algorithm it uses to sign tokens, and it's not safe to allow attackers to provide this value."

the current implementation of `jwt` only requires the user to specify either a key or a secret. They cannot specify both. Hence, this works as an "implicit" algorithm parameter and the server already knows what algorithm it uses to sign tokens.

**Comment by pr130** [comment]
maybe we should turn the warning if secret is empty into an error though. 🤔

**Comment by jandix** [comment]
And warnings should definitely go into docs.

**Comment by pr130** [comment]
- turn wanring into error in code
- add warnings regarding storage of JWT that cause security risks (cookies vs / & local storage) to README.

**Comment by pr130** [comment]
warning is turned into error. tests are adapted. 

adaption of docs / README still tbd. maybe wait until we have a model for the website.

**Comment by pr130** [comment]
closing this issue and adding a new one for extending docs with warnings.
